/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;


import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Robert
 */
public class frmUserExercicios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmUserExercicios
     */
    public frmUserExercicios() {
        initComponents();
        grupo();
    }
Conexao_bd bd = new Conexao_bd();
public void cbk(){
        int cod = ckbGrupo.getSelectedIndex();
        
      String preencher;
      
        preencher = "select descricao from exercicios where grupo_ex =" + cod;
        if(cod == 0){
             preencher = "select descricao from exercicios where " ;
        }
        try{
            ResultSet rs = bd.executarconsulta(preencher);
            ResultSetMetaData rsmd = rs.getMetaData();
            int num_coluna = rsmd.getColumnCount();
            DefaultTableModel pesq_pag = new DefaultTableModel();
           tblExercicio.setModel(pesq_pag);
           
            
                 for(int x=1; x <= num_coluna ; x++){
                pesq_pag.addColumn(rsmd.getColumnLabel(x));
                }
            
                 while(rs.next()){

                    Object [] file = new Object[num_coluna];
                
                     for(int y=0 ; y < num_coluna ; y++)
                    {
                      file[y] = rs.getObject(y+1);
                      ArrayList list = new ArrayList();
                  list.add(rs.getObject(y+1));
                  ckbExercicio.addItem(list);
                    }
                    pesq_pag.addRow(file);
                  
                 }
                 
        }
                 catch(SQLException ex) {
            System.out.println("Erro na consulta");
            System.out.println(preencher);
            
                 }
       }
 public void grupo(){ String preencher;
        preencher = "select descricao from  grupoexercicios ";
        try{
            ResultSet rs = bd.executarconsulta(preencher);
            ResultSetMetaData rsmd = rs.getMetaData();
            int num_coluna = rsmd.getColumnCount();
            DefaultTableModel pesq_pag = new DefaultTableModel();
           
           
            
                 for(int x=1; x <= num_coluna ; x++){
                pesq_pag.addColumn(rsmd.getColumnLabel(x));
                }
            
                 while(rs.next()){

                    Object [] file = new Object[num_coluna];
                
                     for(int y=0 ; y < num_coluna ; y++)
                    {
                      file[y] = rs.getObject(y+1);
                      ArrayList list = new ArrayList();
                  list.add(rs.getObject(y+1));
                  ckbGrupo.addItem(list);
                    }
                    pesq_pag.addRow(file);
                  
                 }
                 
        }
                 catch(SQLException ex) {
            System.out.println("Erro na consulta");
            System.out.println(preencher);
            
                 }}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ckbExercicio = new javax.swing.JComboBox();
        ckbGrupo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblExercicio = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        ckbExercicio.setMaximumRowCount(60);
        ckbExercicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---------" }));

        ckbGrupo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------" }));
        ckbGrupo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbGrupoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Grupo de Exercicio");

        jLabel5.setText("Exercicios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(ckbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addComponent(ckbExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        tblExercicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblExercicio.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tblExercicioComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tblExercicio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbGrupoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbGrupoItemStateChanged
        // TODO add your handling code here:
        ckbExercicio.removeAllItems();
        cbk();
    }//GEN-LAST:event_ckbGrupoItemStateChanged

    private void tblExercicioComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblExercicioComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_tblExercicioComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ckbExercicio;
    private javax.swing.JComboBox ckbGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblExercicio;
    // End of variables declaration//GEN-END:variables
}
