/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;


import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Robert
 */
public class frmListaPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaPagamento
     */
    public frmListaPagamento() {
        initComponents();
    }
Conexao_bd bd = new Conexao_bd();
public String sql,mes,tipo; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMensalidades = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJan = new javax.swing.JRadioButton();
        btnFev = new javax.swing.JRadioButton();
        btnMar = new javax.swing.JRadioButton();
        btnAbr = new javax.swing.JRadioButton();
        btnJun = new javax.swing.JRadioButton();
        btnJul = new javax.swing.JRadioButton();
        btnSet = new javax.swing.JRadioButton();
        btnAgo = new javax.swing.JRadioButton();
        btnOut = new javax.swing.JRadioButton();
        btnNov = new javax.swing.JRadioButton();
        btnMai = new javax.swing.JRadioButton();
        btnDez = new javax.swing.JRadioButton();
        btnAberto = new javax.swing.JRadioButton();
        btnPago = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lsita de Pagamentos");

        tblMensalidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMensalidades);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mês");

        buttonGroup1.add(btnJan);
        btnJan.setText("Janeiro");

        buttonGroup1.add(btnFev);
        btnFev.setText("Fevereiro");

        buttonGroup1.add(btnMar);
        btnMar.setText("Março");

        buttonGroup1.add(btnAbr);
        btnAbr.setText("Abril");

        buttonGroup1.add(btnJun);
        btnJun.setText("Junho");

        buttonGroup1.add(btnJul);
        btnJul.setText("Julho");

        buttonGroup1.add(btnSet);
        btnSet.setText("Setembro");

        buttonGroup1.add(btnAgo);
        btnAgo.setText("Agosto");

        buttonGroup1.add(btnOut);
        btnOut.setText("Outubro");

        buttonGroup1.add(btnNov);
        btnNov.setText("Novembro");

        buttonGroup1.add(btnMai);
        btnMai.setText("Maio");

        buttonGroup1.add(btnDez);
        btnDez.setText("Dezembro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJun)
                    .addComponent(btnAbr)
                    .addComponent(btnMar)
                    .addComponent(btnFev)
                    .addComponent(btnJan)
                    .addComponent(btnMai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNov)
                    .addComponent(btnOut)
                    .addComponent(btnSet)
                    .addComponent(btnAgo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDez)
                    .addComponent(btnJul))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnJan)
                            .addComponent(btnJul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOut)
                            .addComponent(btnAbr))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMai)
                    .addComponent(btnNov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDez)
                    .addComponent(btnJun))
                .addGap(93, 93, 93))
        );

        btnAberto.setText("Abertos");

        btnPago.setText("Pagos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(jButton1)))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnPago)
                            .addGap(18, 18, 18)
                            .addComponent(btnAberto)
                            .addGap(31, 31, 31)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPago)
                                .addComponent(btnAberto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(btnPago.isSelected()){
            tipo = "pago";
        }
        if(btnAberto.isSelected()){
            tipo = "aberto";
        }
        
        if(btnJan.isSelected()){
            mes="janeiro";
        }
        if(btnFev.isSelected()){
            mes="fevereiro";
        }
        if(btnMar.isSelected()){
            mes="marco";
        }
        if(btnAbr.isSelected()){
            mes="abril";
        }
        if(btnMai.isSelected()){
            mes="maio";
        }
        if(btnJun.isSelected()){
            mes="junho";
        }
        if(btnJul.isSelected()){
            mes="julho";
        }
        if(btnAgo.isSelected()){
            mes="agosto";
        }
        if(btnSet.isSelected()){
            mes="setembro";
        }
        if(btnOut.isSelected()){
            mes="outubto";
        }
        if(btnNov.isSelected()){
            mes="novembroo";
        }
        if(btnDez.isSelected()){
            mes = "dezembro";
        }
        sql = "select a.cpf,b.nome from mensalidades a inner join cliente b "
        + "on  a." + mes + " = '" + tipo +"' ";
        //buscarnome();
       if(btnAberto.isSelected() && btnPago.isSelected()){
        sql = "select a.cpf,b.nome from mensalidades a inner join cliente b ";
        
        }
    
        
        try{
            ResultSet rs = bd.executarconsulta(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            int num_coluna = rsmd.getColumnCount();
            DefaultTableModel pesq_pag = new DefaultTableModel();
            this.tblMensalidades.setModel(pesq_pag);
           
            
                 for(int x=1; x <= num_coluna ; x++){
                pesq_pag.addColumn(rsmd.getColumnLabel(x));
                }
            
                 while(rs.next()){
     
                    Object [] file = new Object[num_coluna];
                
                     for(int y=0 ; y < num_coluna ; y++)
                    {
                      file[y] = rs.getObject(y+1);
                    }
                    pesq_pag.addRow(file);
                 }
                 
        }
        catch(SQLException ex) {
            System.out.println("Erro na consulta");
            System.out.println(sql);

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAberto;
    private javax.swing.JRadioButton btnAbr;
    private javax.swing.JRadioButton btnAgo;
    private javax.swing.JRadioButton btnDez;
    private javax.swing.JRadioButton btnFev;
    private javax.swing.JRadioButton btnJan;
    private javax.swing.JRadioButton btnJul;
    private javax.swing.JRadioButton btnJun;
    private javax.swing.JRadioButton btnMai;
    private javax.swing.JRadioButton btnMar;
    private javax.swing.JRadioButton btnNov;
    private javax.swing.JRadioButton btnOut;
    private javax.swing.JRadioButton btnPago;
    private javax.swing.JRadioButton btnSet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMensalidades;
    // End of variables declaration//GEN-END:variables
}
