/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;


import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Robert
 */
public class frmListarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListarClientes
     */
    public frmListarClientes() {
        initComponents();
        consulta();
    }
    
    Conexao_bd bd = new Conexao_bd();
public void consulta (){
    String sql = "select * from cliente";
        
        try{
            ResultSet rs = bd.executarconsulta(sql);
            ResultSetMetaData rsmd = rs.getMetaData();
            int num_coluna = rsmd.getColumnCount();
            DefaultTableModel pesq_clientes = new DefaultTableModel();
            
            this.tblClientes.setModel(pesq_clientes);
           
                 for(int x=1; x <= num_coluna ; x++){
                pesq_clientes.addColumn(rsmd.getColumnLabel(x));
                }
            
                 while(rs.next()){
                
                    Object [] file = new Object[num_coluna];
                
                     for(int y=0 ; y < num_coluna ; y++)
                    {
                      file[y] = rs.getObject(y+1);
                    }
                    pesq_clientes.addRow(file);
                 }}
                 catch(SQLException ex) {
            System.out.println("Erro na consulta");
                 }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Clientes");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClientes.setMaximumSize(new java.awt.Dimension(2147483647, 6400));
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
