/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package academia;


import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Robert
 */
public class frmPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPagamento
     */
    public frmPagamento() {
        initComponents();
        pnlPagamento.setVisible(false);
    }
Conexao_bd bd = new Conexao_bd();
       
       
       public void mensal (){
       
       String salvar="";
       
       
       if(btnJan.isSelected()){
        salvar = "update mensalidades set janeiro = 'Pago' where cpf='" + txtCpf.getText() + "'";
        bd.executarcomandos(salvar);
       }
       if(btnFev.isSelected()){
        salvar = "update mensalidades set fevereiro = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
        if(btnMar.isSelected()){
        salvar = "update mensalidades set marco = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
       if(btnAbr.isSelected()){
        salvar = "update mensalidades set abril = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
        if(btnMai.isSelected()){
        salvar = "update mensalidades set maio = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
       if(btnJun.isSelected()){
        salvar = "update mensalidades set junho = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
        if(btnJul.isSelected()){
        salvar = "update mensalidades set julho = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
        }
       if(btnAgo.isSelected()){
        salvar = "update mensalidades set agosto = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
        }
       if(btnSet.isSelected()){
        salvar = "update mensalidades set setembro = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
         }
        if(btnOut.isSelected()){
        salvar = "update mensalidades set outubro = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
       }
        if(btnNov.isSelected()){
        salvar = "update mensalidades set novembro = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
        }
       if(btnDez.isSelected()){
        salvar = "update mensalidades set dezembro = 'Pago' where cpf='" + txtCpf.getText() + "'";
         bd.executarcomandos(salvar);
        }
       JOptionPane.showMessageDialog(null,"Pagamento realizado");
       }
       public double mens;
       public double total;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValidar = new javax.swing.JButton();
        pnlPagamento = new javax.swing.JPanel();
        lvlPrest = new javax.swing.JLabel();
        lblRecebido = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        txtPagar = new javax.swing.JFormattedTextField();
        txtRecebido = new javax.swing.JFormattedTextField();
        btnCalcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJan = new javax.swing.JRadioButton();
        btnFev = new javax.swing.JRadioButton();
        btnMar = new javax.swing.JRadioButton();
        btnAbr = new javax.swing.JRadioButton();
        btnJun = new javax.swing.JRadioButton();
        btnJul = new javax.swing.JRadioButton();
        btnSet = new javax.swing.JRadioButton();
        btnAgo = new javax.swing.JRadioButton();
        btnOut = new javax.swing.JRadioButton();
        btnNov = new javax.swing.JRadioButton();
        btnMai = new javax.swing.JRadioButton();
        btnDez = new javax.swing.JRadioButton();
        txtTroco = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        lblCPF = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Realizar Pagamento");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        pnlPagamento.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlPagamentoComponentShown(evt);
            }
        });
        pnlPagamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pnlPagamentoInputMethodTextChanged(evt);
            }
        });

        lvlPrest.setText("Valor a ser pago");

        lblRecebido.setText("Valor Recebido");

        lblTroco.setText("Troco");
        lblTroco.setToolTipText("");

        txtPagar.setEditable(false);
        try {
            txtPagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRecebido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel1.setText("Mês");

        btnJan.setText("Janeiro");

        btnFev.setText("Fevereiro");

        btnMar.setText("Março");

        btnAbr.setText("Abril");

        btnJun.setText("Junho");

        btnJul.setText("Julho");

        btnSet.setText("Setembro");

        btnAgo.setText("Agosto");

        btnOut.setText("Outubro");

        btnNov.setText("Novembro");

        btnMai.setText("Maio");

        btnDez.setText("Dezembro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJun)
                    .addComponent(btnAbr)
                    .addComponent(btnMar)
                    .addComponent(btnFev)
                    .addComponent(btnJan)
                    .addComponent(btnMai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNov)
                    .addComponent(btnOut)
                    .addComponent(btnSet)
                    .addComponent(btnAgo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDez)
                    .addComponent(btnJul))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnJan)
                            .addComponent(btnJul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOut)
                            .addComponent(btnAbr))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMai)
                    .addComponent(btnNov))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDez)
                    .addComponent(btnJun))
                .addGap(93, 93, 93))
        );

        txtTroco.setEditable(false);
        txtTroco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnPagar.setText("Troco");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPagamentoLayout = new javax.swing.GroupLayout(pnlPagamento);
        pnlPagamento.setLayout(pnlPagamentoLayout);
        pnlPagamentoLayout.setHorizontalGroup(
            pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagamentoLayout.createSequentialGroup()
                .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagamentoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lvlPrest)
                            .addComponent(lblRecebido)
                            .addComponent(lblTroco)))
                    .addGroup(pnlPagamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)))
                .addGap(18, 18, 18)
                .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPagar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(txtTroco))
                .addGap(18, 18, 18)
                .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPagamentoLayout.setVerticalGroup(
            pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPagamentoLayout.createSequentialGroup()
                .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPagamentoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar))
                    .addGroup(pnlPagamentoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lvlPrest)
                            .addComponent(txtPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecebido))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTroco)
                            .addComponent(txtTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPagamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCPF.setText("CPF:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(lblCPF)
                            .addGap(22, 22, 22)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(303, 303, 303)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnValidar))
                    .addGap(18, 18, 18)
                    .addComponent(pnlPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnSalvar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        String sql = "select a.janeiro,a.fevereiro,a.marco,a.abril,a.maio,"
        + "a.junho,a.julho,a.agosto,a.setembro,a.outubro,a.novembro, "
        + "a.dezembro ,c.valor from mensalidades a inner join cliente b inner join planos c "
        + "on a.cpf='" +  txtCpf.getText() + "' and b.cod_plano = c.cod_plano ;";
        boolean nao_achou = true;

        try{
            ResultSet rs = bd.executarconsulta(sql);

            while (rs.next())
            {
                //se consulta for ok o campo valor do recebe a mensalidade do user  consultado
                txtPagar.setText(rs.getString("valor"));
                mens = rs.getDouble("valor");
                pnlPagamento.setVisible(true);
                nao_achou = false;
            }

            if(nao_achou){

                JOptionPane.showMessageDialog(null,"Cliente nao cadastrado");
            }

        }
        catch (SQLException ex){
            System.out.println("Error na busca");
            System.out.println(sql);
        }

    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        if(btnJan.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnFev.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnMar.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnAbr.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnMai.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnJun.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnJul.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnAgo.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnSet.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnOut.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnNov.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }
        if(btnDez.isSelected()){

            total = total + mens;
            txtPagar.setText(""+ total);
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        double troco;

        troco = Double.parseDouble(txtRecebido.getText())- Double.parseDouble(txtPagar.getText()) ;

        txtTroco.setText("" + troco);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void pnlPagamentoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlPagamentoComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlPagamentoComponentShown

    private void pnlPagamentoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pnlPagamentoInputMethodTextChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_pnlPagamentoInputMethodTextChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if(Double.parseDouble(txtTroco.getText())>=0.00){
            mensal();
        }

    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAbr;
    private javax.swing.JRadioButton btnAgo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JRadioButton btnDez;
    private javax.swing.JRadioButton btnFev;
    private javax.swing.JRadioButton btnJan;
    private javax.swing.JRadioButton btnJul;
    private javax.swing.JRadioButton btnJun;
    private javax.swing.JRadioButton btnMai;
    private javax.swing.JRadioButton btnMar;
    private javax.swing.JRadioButton btnNov;
    private javax.swing.JRadioButton btnOut;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JRadioButton btnSet;
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblRecebido;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lvlPrest;
    private javax.swing.JPanel pnlPagamento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtPagar;
    private javax.swing.JFormattedTextField txtRecebido;
    private javax.swing.JTextField txtTroco;
    // End of variables declaration//GEN-END:variables
}
